### ISSUE TITLE
Is it possible to use this strong baseline on binding affinity prediction?

### ISSUE THREAD

**Issue by josiehong** [inductive-bio/strong-docking-baseline#2]
Nice work! 

I am interested in binding affinity prediction on virtual screening. Can I utilize this model to do that? 

Thanks,
Josie

**Comment by alexanderrich** [comment]
Hi Josie, you could definitely use a modified version of this code to predict binding affinity. A couple of things to note:
* You would want to use gnina's `CNNaffinity` output to compare affinity across ligands, rather than the `CNNscore` output that is intended for ranking poses within a ligand.
* The code here isn't really optimized for speed. If you want to screen large libraries, you could consider using something like [Uni-dock](https://github.com/dptech-corp/Uni-Dock) that can take advantage of a GPU to greatly speed up pose sampling (gnina only uses the GPU for scoring poses after they are sampled), and then use gnina to rank the generated poses.

**Comment by josiehong** [comment]
It is very helpful! Thank you so much.
